<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "teste-1": {
        "title": "teste 1",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2018-11-01 17:38:44",
        "dateModified": "",
        "position": 2,
        "coverImage": "",
        "category": "",
        "md5file": "ef0c66fb658c161b9fa4311261f10043",
        "uuid": "140d30225c525a7358d363af3a3ccd20",
        "allowComments": true,
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false,
        "custom": []
    },
    "sobre": {
        "title": "Sobre",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "static",
        "date": "2018-11-01 17:31:31",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "257d6b04ce3300c91547abd47c109330",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "siga-os-canais-oficiais-do-bludit": {
        "title": "Siga os canais oficiais do Bludit",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2018-11-01 17:31:31",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "871bad281d225af0ec7f6479334d2e06",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "aproveite-e-va-ajustando-o-seu-site": {
        "title": "Aproveite e v\u00e1 ajustando o seu site",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2018-11-01 17:31:31",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "0adba5af1faec3f723f3d8294249a879",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "crie-o-seu-proprio-conteudo": {
        "title": "Crie o seu pr\u00f3prio conte\u00fado",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2018-11-01 17:31:31",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "13f05ae73f6b6ba117dd532ba8325b66",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    }
}